config/routes.rb
Recipes::Application.routes.draw do
  resources :types

  resources :meals

  root :to => 'meals#index'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :title, :notes, :url, :type_id, :healthy

  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name

  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to meals_path, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to meals_path, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to types_path, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/meals/_form.html.erb
<%= simple_form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :title, wrapper_html: { class: 'field' }, input_html: { class: 'text input' } %>
    <%= f.input :type_id, :collection => Type.all, :selected => @meal.type_id  %>
    <%= f.input :healthy, label: 'Is Healthy?' %>
    <%= f.input :url, wrapper_html: { class: 'field' }, input_html: { class: 'text input' } %>
    <%= f.input :notes, :as => :ckeditor, rows: 5, wrapper_html: { class: 'field' }, input_html: { rows: 7, class: 'textarea input' } %>
  <div class="btn rounded metro medium primary">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<div class="twelve columns">
<h1>Listing meals</h1>

<% @meals.each do |meal| %>

    <div class="card">
      <div class="card-title clearfix">
      <h3 class="meal-name"><%= meal.title %>
      <% if meal.healthy %> <i class="icon-leaf"></i><% end %>
      </h3>
      <h5 class="meal-type"><%= meal.type.name %></h5>
      </div>
      <div class="card-data">
          <p>
            <%=raw meal.notes %>
          </p>
                    <% if meal.url != "" %>
            <div class="btn medium metro warning rounded">
              <a target="_blank" href="<%= meal.url %>">View External Recipe</a>
            </div>
          <% end %>
          <div class="edit">
                <%= link_to(edit_meal_path(meal))  do %>
                  <i class="icon-pencil"></i>
                <% end %>
                <%= link_to(meal, method: :delete, data: { confirm: 'Are you sure?' }) do %>
                  <i class="icon-cancel-squared"></i>
                <% end %>
              </div>
      </div>
    </div>
<% end %>


<br />
<div class="btn medium metro primary rounded">
<%= link_to 'New Meal', new_meal_path %>
</div>
</div>

app/views/meals/new.html.erb
<div class="fourteen columns">
<h1>New meal</h1>

<%= render 'form' %>
	<div class="btn metro rounded medium danger">
		<%= link_to 'Back', meals_path %>
	</div>
</div>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @meal.title %>
  <%= @meal.url %>
  <%= @meal.notes %>
</p>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, wrapper_html: { class: 'field' }, input_html: { class: 'text input' }  %>
  <div class="btn rounded metro medium primary">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.name %></td>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<div class="fourteen columns">
<h1>New Meal Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>
</div>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>